### ISSUE TITLE
How to overlap Raster layer correctly 

### ISSUE THREAD

**Issue by seifer08ms** [fkeck/rleafmap#2]
Hi, I have a trouble overlaping a raster image on the leafletmap. The geojson layer is perfect but raster layer is drifting off the boundary . Here is my testing code ::

require(raster)
require(maptools)
cdem<-getData('alt',country='CHN')
cdem<-aggregate(cdem,8)
xian.bd09<-as.numeric(baidumap::getCoordinate('beijing',formatted=T))
require(rleafmap)
cdem.sp<-as(cdem,'SpatialGridDataFrame')
cdem.spl<-spLayer(cdem.sp, layer='CHN_msk_alt',
                  cells.alpha = seq(0.1, 0.8, length.out = 12))
cn.admin<-getData('GADM',country='CN',level=0)
require(rgeos)
cn.admin <- gSimplify(cn.admin, 0.9, topologyPreserve=T)
cn.admin.spl<-spLayer(cn.admin, fill.col = 1)
bm2<-basemap("stamen.toner")
bm1 <- basemap("mapquest.map")
my.ui <- ui(layers = "topright")
writeMap(bm2,bm1,width = 1000,height =500,cdem.spl,
         cn.admin.spl,setView=rev(xian.bd09),interface = my.ui,setZoom=4)

**Comment by fkeck** [comment]
Hi, thanks for the report. I checked your code and there is, indeed, a problem.
Probably the raster image is not generated correctly by rleafmap. It appears clearly when you work on large area like China.
This is a concerning problem, I already had a lot of troubles with rasters display. I hope I could fix this quickly, but any help or suggestions are welcome.

**Comment by seifer08ms** [comment]
Thanks for your quickly reply. I am looking forward to the next version . Actually, I have learned many leaflet mapping details without deploying raster tiles server from rleafmap and hope I could luckily found some clues to help .

**Comment by fkeck** [comment]
Hi, I think the bug is fixed now. It was a problem of projection. Thanks for the report.

**Comment by seifer08ms** [comment]
Thanks a lot. Now it works and I'm HAPPY :) :+1:
