### ISSUE TITLE
feature request: legend option for writemap 

### ISSUE THREAD

**Issue by seifer08ms** [fkeck/rleafmap#3]
Pls take into consideration the need of legend option for map. I believe this will help rleafmap become more attractive for users.

**Comment by fkeck** [comment]
Thanks for the feedback. I'm working on a legend system for a while. It's not ready yet and I haven't so much time to spend on it. I cannot give a date for a release. It will be something quite flexible but less 'automatic' than what I've seen so far.

**Comment by fkeck** [comment]
Hi,
Legends are now available.
See the related blog post: http://www.pieceofk.fr/?p=376
