### ISSUE TITLE
Campsite ratings do not appear

### ISSUE THREAD

**Issue by pssguy** [fkeck/rleafmap#6]
I downloaded the campsites data directly from this site #5  but when I run code (replacing mapquest with stamen #4 ) the popup does not show stars although are in pop

```
> pop
 [1] "AIN (01) <br>1★ <br>9★★ <br>23★★★ <br>9★★★★ <br>0★★★★★"
```

![rleafmap issue](https://cloud.githubusercontent.com/assets/2775918/17913266/a80beb30-694d-11e6-8d3a-8e186ef61162.png)

BTW looks great package

**Comment by fkeck** [comment]
Hi, I couldn't reproduce your issue. This is likely a problem of your viewer (RStudio viewer, web browser? -- did you try different ones?) which fails to print the 'star' character.

**Comment by pssguy** [comment]
RStudio and Chrome.

**Comment by fkeck** [comment]
That's really weird. It works for me in RStudio, Firefox and Chromium. Can you check that the stars are correctly written in the file _data/_datapolygons.js ?

**Comment by pssguy** [comment]
I do not have a specific js viewer, if that is needed. As mentioned above, the stars do appear in console of RStudio

**Comment by fkeck** [comment]
I suspect the problem comes from your locale (especially if you are on Windows). I tried to fix it but this is hard for me because I cannot reproduce your problem. Can you reinstall rleafmap from github (very last version) and tell me if the issue persists? Thank you.

**Comment by pssguy** [comment]
Still an issue and yes I am on Windows :(

**Comment by fkeck** [comment]
I tried something else. Hope it works.

**Comment by pssguy** [comment]
Looks good!
Thanks for your time and effort
